server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  application:
    name: shop-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/electroShopDb
    username: root
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/